version: 2.1
jobs:
  build:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test
    environment:
      CHROME_BIN: "C:\Program Files\Google\Chrome\Application\chrome.exe"
    - run: echo $CHROME_BIN