version: 2.1

jobs:
  build:
    docker:
      - image: node:16

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install

      - run:
          name: Build Project
          command: |
            npm run build
